# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Winterlong"
license = "MIT"
licenselink = "https://github.com/drmdrew/winterlong/blob/master/LICENSE.md"
description = "Winterlong is a hugo blog theme"
homepage = "https://drmdrew.ca/winterlong"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Drew MacInnis"
  homepage = "https://dreamdrew.ca"
